### ISSUE TITLE
cannot reproduce the sample result.

### ISSUE THREAD

**Issue by PressFforlove** [ychen306/vegen#44]
Hi there, thank you for reading this issue.
i have a test.c like below(which is the same with the sample code in paper).
```
#include <stdint.h>
void
dot_16x1x16_uint8_int8_int32 (
uint8_t data [ restrict 4],
int8_t kernel [ restrict 16][4] ,
int32_t output [ restrict 16]) {
for ( int i = 0; i < 16; i ++)
for ( int k = 0; k < 4; k ++)
output [i] +=
data [k] * kernel [i][k];
}

```
i tried to use vegen-clang -S -O3 -ffast-math -march=native test.c -o test,（and also tried 
-mavx512vnni） to reproduce the result paper showed in Figure2(which uses _vpdpbusd_)，however, i cant success. and i don't know why. 
any help is appreciated~

**Comment by PressFforlove** [comment]
and i tried compile with `CXX = gcc` and `CXX = clang12`，which give me the same result.

**Comment by ychen306** [comment]
That's due to a pre-processing transformation we introduced (after the paper) where we balance reduction trees (e.g., `a + b + c + d` => `(a + b) + (c + d)`) but break the pattern matcher. You can disable that transformation with `-mllvm -no-balance-rdx`:
```bash
 $ vegen-clang test.c -S -O3 -march=icelake-server  -mllvm -no-balance-rdx -o -
```

We are working on a rewrite of VeGen where pattern matching on reduction operators is more robust (e.g., regarding reassociation), but the code is not public yet.

**Comment by PressFforlove** [comment]
thank you very much~
